In [1]:
import numpy as np

In [2]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [3]:
np.arange(3,4
         )

array([3])

In [4]:
np.arange(1,29)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28])

In [5]:
np. twos(4
        )

AttributeError: module 'numpy' has no attribute 'twos'

In [6]:
np.ones(3
       )

array([1., 1., 1.])

In [7]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
np.linspace(0,5,30
           )

array([0.        , 0.17241379, 0.34482759, 0.51724138, 0.68965517,
       0.86206897, 1.03448276, 1.20689655, 1.37931034, 1.55172414,
       1.72413793, 1.89655172, 2.06896552, 2.24137931, 2.4137931 ,
       2.5862069 , 2.75862069, 2.93103448, 3.10344828, 3.27586207,
       3.44827586, 3.62068966, 3.79310345, 3.96551724, 4.13793103,
       4.31034483, 4.48275862, 4.65517241, 4.82758621, 5.        ])

In [20]:
np.linspace(0,5)

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

In [21]:
 np.random.rand(5)

array([0.2643891 , 0.44513211, 0.11933724, 0.76246235, 0.97913924])

In [22]:
np.random.range(2,3
               )

AttributeError: module 'numpy.random' has no attribute 'range'

In [23]:
np.random.rand(2,3)

array([[0.54928076, 0.15042827, 0.24249357],
       [0.2348883 , 0.91570029, 0.83219515]])

In [26]:
np.random.randint(69,100,4)

array([73, 81, 84, 70])

In [30]:
arr =  np.arange(25)

In [31]:
arr



array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [34]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [35]:
arr.max()


24

In [36]:
arr.min()

0

In [38]:
arr.argmax()

24

In [39]:
arr.argmin()

0

In [42]:
arr.shape

(25,)

In [43]:
from numpy.random import randint as rd

In [47]:
rd(2,10)

8

In [48]:
import numpy as np

In [50]:
arr = np.random.randint(2,100,10)

In [51]:
arr

array([69, 67, 61, 67, 22, 92,  4, 55, 19, 19])

In [52]:
arr[8]

19

In [53]:
arr[2:5]

array([61, 67, 22])

In [54]:
 reverse = arr[::-1]

In [55]:
reverse

array([19, 19, 55,  4, 92, 22, 67, 61, 67, 69])

In [60]:
 big = reverse.reshape(2,5)


In [61]:
big

array([[19, 19, 55,  4, 92],
       [22, 67, 61, 67, 69]])

In [62]:
big[0][1]

19

In [63]:
big[0,1]

19

In [64]:
import numpy as np

In [68]:
array = np.arange(25)

In [69]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [72]:
arr =array.reshape(5,5,)

In [73]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [79]:
arrays = arr[2:4,2:]

In [80]:
arrays

array([[12, 13, 14],
       [17, 18, 19]])

In [82]:
arrays[arrays<15]

array([12, 13, 14])

In [83]:
# assigment
arrays = np.arange(50).reshape(5,10)

In [84]:
arrays

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [89]:
arrays[1:3,1:3]

array([[11, 12],
       [21, 22]])